version: "3.8"

services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 80
