version: '3.8'

services:
  web:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  test:
    build:
      context: ./app
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: ["pytest"]
